<a href="https://colab.research.google.com/github/itskutush/Water-Quality-Analysis-using-GNN/blob/Data-Analysis1/Research_test_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sns

In [2]:
df = pd.read_csv('datasetfinal.csv')

In [3]:
df

,Year,Monitoring Location,Type of Water Body,State,Min Temp (20<),Max Temp (>30),Min Dissolved O2(mg/L),MaxDissolved O2(mg/L),Min pH(7.5<),Max pH(>8.4),Min Conductivity (μmho/cm)(<30k),Max Conductivity (μmho/cm)(>50k),Min BOD\n(mg/L)(<5),Max BOD\n(mg/L)(>5),Min NitrateN + NitriteN (mg/L)(<0.3),Max NitrateN + NitriteN (mg/L)(>0.5),Min Fecal Coliform (MPN/100ML),Max Fecal Coliform (MPN/100ML) (<200),Min Total Coliform (MPN/100ML),Max Total Coliform (MPN/100ML)
0,2022,"SEA WATER, BAY OF BENGAL, AFTER CONFLUENCE OF ...",MARINE,ANDHRA PRADESH,21.0,30.0,5.2,7.2,7.4,8.4,13800.0,57300.0,1.2,2.5,0.32,1.38,3.0,7.0,48.0,120.0
1,2022,CONFLUENCE OF MARINE OUTFALL OF M/S MATRIX LAB...,MARINE,ANDHRA PRADESH,25.0,28.0,5.2,6.6,7.7,8.5,32200.0,56400.0,1.4,2.8,0.32,0.88,3.0,11.0,39.0,210.0
2,2022,"RUSHIKONDA BEACH,VISAKHAPATNAM",BEACH,ANDHRA PRADESH,25.0,29.0,4.8,7.0,7.7,8.5,31700.0,55700.0,1.2,2.9,0.32,1.13,3.0,14.0,39.0,150.0
3,2022,"SEA WATER BAY BENGAL, UPPADA BEACH ROAD, KAKIN...",BEACH,ANDHRA PRADESH,25.0,28.0,4.5,7.9,7.8,8.5,4800.0,51400.0,2.2,2.8,0.42,1.32,3.0,20.0,48.0,150.0
4,2022,"WATER PORT, KAKINADA (1KM AWAY FROM JETTY)",SEA,ANDHRA PRADESH,25.0,27.0,5.3,8.0,7.4,8.4,861.0,50300.0,2.2,3.9,0.82,3.32,4.0,23.0,75.0,460.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,2018,ATHARABANKI CREEK,CREEK,ODISHA,21.0,30.0,2.6,8.2,6.7,7.7,146.0,28760.0,0.8,7.9,0.25,4.09,1.8,16000.0,20.0,16000.0
231,2017,PURI,CREEK,ODISHA,21.0,31.0,5.4,7.3,7.7,8.2,31670.0,59240.0,0.6,3,0.35,2.59,5.0,5400.0,21.0,9200.0
232,2017,PARADEEP,CREEK,ODISHA,21.0,30.0,5.8,8.5,7.4,8.2,32190.0,62520.0,0.3,1.4,0.11,3.84,2.0,45.0,2.0,78.0
233,2017,GOPALPUR,CREEK,ODISHA,10.0,30.0,5.2,7.7,7.8,8.4,34408.0,58050.0,0.3,1.8,0.24,2.55,2.0,130.0,2.0,230.0
234,2017,ATHARABANKI CREEK,CREEK,ODISHA,24.0,31.0,2.6,5.9,5.6,7.2,1296.0,28770.0,2.3,9.3,0.57,3.90,790.0,22000.0,330.0,54000.0

In [4]:
columns_to_convert = ['Min BOD\n(mg/L)(<5)','Max BOD\n(mg/L)(>5)']
columns_to_convert2 =['Monitoring Location','Type of Water Body','State']



for column in columns_to_convert:
    # Replace empty strings with NaN
    df[column] = df[column].replace('', np.nan)
    # Convert non-numeric strings to NaN
    df[column] = pd.to_numeric(df[column], errors='coerce')
for column in columns_to_convert2:
    df[column] = df[column].astype(str)

In [5]:
df.dtypes

Year                                       int64
Monitoring Location                       object
Type of Water Body                        object
State                                     object
Min Temp (20<)                           float64
Max Temp (>30)                           float64
Min Dissolved O2(mg/L)                   float64
MaxDissolved O2(mg/L)                    float64
Min pH(7.5<)                             float64
Max pH(>8.4)                             float64
Min Conductivity (μmho/cm)(<30k)         float64
Max Conductivity (μmho/cm)(>50k)         float64
Min BOD\n(mg/L)(<5)                      float64
Max BOD\n(mg/L)(>5)                      float64
Min NitrateN + NitriteN (mg/L)(<0.3)     float64
Max NitrateN + NitriteN (mg/L)(>0.5)     float64
Min Fecal Coliform (MPN/100ML)           float64
Max Fecal Coliform (MPN/100ML) (<200)    float64
Min Total Coliform (MPN/100ML)           float64
Max Total Coliform (MPN/100ML)           float64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 20 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Year                                   235 non-null    int64
 1   Monitoring Location                    235 non-null    object
 2   Type of Water Body                     235 non-null    object
 3   State                                  235 non-null    object
 4   Min Temp (20<)                         189 non-null    float64
 5   Max Temp (>30)                         189 non-null    float64
 6   Min Dissolved O2(mg/L)                 235 non-null    float64
 7   MaxDissolved O2(mg/L)                  235 non-null    float64
 8   Min pH(7.5<)                           235 non-null    float64
 9   Max pH(>8.4)                           235 non-null    float64
 10  Min Conductivity (μmho/cm)(<30k)       69 non-null     float64
 11  Max Conductivity (μmho/cm)(>50k)       69 non-null     float64
 12  Min BOD
(mg/L)(<5)                     216 non-null    float64
 13  Max BOD
(mg/L)(>5)                     217 non-null    float64
 14  Min NitrateN + NitriteN (mg/L)(<0.3)   67 non-null     float64
 15  Max NitrateN + NitriteN (mg/L)(>0.5)   67 non-null     float64
 16  Min Fecal Coliform (MPN/100ML)         226 non-null    float64
 17  Max Fecal Coliform (MPN/100ML) (<200)  226 non-null    float64
 18  Min Total Coliform (MPN/100ML)         74 non-null     float64
 19  Max Total Coliform (MPN/100ML)         74 non-null     float64
dtypes: float64(16), int64(1), object(3)
memory usage: 36.8+ KB

In [7]:
df.describe()

,Year,Min Temp (20<),Max Temp (>30),Min Dissolved O2(mg/L),MaxDissolved O2(mg/L),Min pH(7.5<),Max pH(>8.4),Min Conductivity (μmho/cm)(<30k),Max Conductivity (μmho/cm)(>50k),Min BOD\n(mg/L)(<5),Max BOD\n(mg/L)(>5),Min NitrateN + NitriteN (mg/L)(<0.3),Max NitrateN + NitriteN (mg/L)(>0.5),Min Fecal Coliform (MPN/100ML),Max Fecal Coliform (MPN/100ML) (<200),Min Total Coliform (MPN/100ML),Max Total Coliform (MPN/100ML)
count,235.000000,189.000000,189.000000,235.000000,235.000000,235.000000,235.000000,69.000000,69.000000,216.000000,217.000000,67.000000,67.000000,226.000000,226.000000,74.000000,74.000000
mean,2021.234043,25.529630,29.409524,5.411064,7.013617,7.572766,8.241277,23662.014493,53117.130435,1.791667,4.039631,0.465015,2.383642,26.264602,414.166814,65.440541,2117.337838
std,1.117322,3.920781,2.263145,1.404406,0.955677,0.597951,0.350882,14679.632545,9532.309889,2.060554,5.137498,0.250689,1.669730,124.975512,1965.464634,67.466075,7304.186732
min,2017.000000,9.000000,21.000000,0.300000,4.800000,5.200000,7.200000,146.000000,12710.000000,0.200000,1.000000,0.110000,0.390000,1.800000,1.800000,1.800000,10.000000
25%,2021.000000,23.000000,28.100000,5.000000,6.350000,7.100000,8.000000,7300.000000,50800.000000,1.000000,1.200000,0.300000,1.282000,2.000000,4.500000,20.250000,120.000000
50%,2022.000000,26.000000,29.500000,5.600000,7.000000,7.600000,8.300000,30900.000000,55700.000000,1.050000,2.500000,0.390000,1.810000,3.000000,15.000000,64.000000,180.000000
75%,2022.000000,28.500000,30.600000,6.200000,7.700000,8.000000,8.500000,32970.000000,57690.000000,2.000000,3.400000,0.645000,2.940000,6.775000,79.000000,73.500000,433.500000
max,2022.000000,32.000000,37.000000,8.400000,12.500000,9.000000,9.300000,55400.000000,74900.000000,20.000000,26.000000,1.240000,8.041000,1600.000000,22000.000000,330.000000,54000.000000

In [8]:
df.isnull().sum()

Year                                       0
Monitoring Location                        0
Type of Water Body                         0
State                                      0
Min Temp (20<)                            46
Max Temp (>30)                            46
Min Dissolved O2(mg/L)                     0
MaxDissolved O2(mg/L)                      0
Min pH(7.5<)                               0
Max pH(>8.4)                               0
Min Conductivity (μmho/cm)(<30k)         166
Max Conductivity (μmho/cm)(>50k)         166
Min BOD\n(mg/L)(<5)                       19
Max BOD\n(mg/L)(>5)                       18
Min NitrateN + NitriteN (mg/L)(<0.3)     168
Max NitrateN + NitriteN (mg/L)(>0.5)     168
Min Fecal Coliform (MPN/100ML)             9
Max Fecal Coliform (MPN/100ML) (<200)      9
Min Total Coliform (MPN/100ML)           161
Max Total Coliform (MPN/100ML)           161
dtype: int64

In [9]:
print(df.columns)

Index(['Year', 'Monitoring Location', 'Type of Water Body', 'State',
       'Min Temp (20<)', 'Max Temp (>30)', 'Min Dissolved O2(mg/L)',
       'MaxDissolved O2(mg/L)', 'Min pH(7.5<)', 'Max pH(>8.4)',
       'Min Conductivity (μmho/cm)(<30k)', 'Max Conductivity (μmho/cm)(>50k)',
       'Min BOD\n(mg/L)(<5)', 'Max BOD\n(mg/L)(>5)',
       'Min NitrateN + NitriteN (mg/L)(<0.3)',
       'Max NitrateN + NitriteN (mg/L)(>0.5)',
       'Min Fecal Coliform (MPN/100ML)',
       'Max Fecal Coliform (MPN/100ML) (<200)',
       'Min Total Coliform (MPN/100ML)', 'Max Total Coliform (MPN/100ML)'],
      dtype='object')

In [10]:
print("Unique states:", df['State'].unique())

Unique states: ['ANDHRA PRADESH ' 'ODISHA ' 'TAMIL NADU ' 'ODISHA' 'ANDHRA PRADESH']

In [11]:
print("Unique Type of Water Body:", df['Type of Water Body'].unique())

Unique Type of Water Body: ['MARINE' 'BEACH ' 'SEA ' 'CREEK ' 'MARINE ' 'SEA  ' 'CREEK' 'SEA']

In [12]:
#Fixing string values
df['State'] = df['State'].replace({'ANDHRA PRADESH  ': 'ANDHRA PRADESH', 'ODISHA ': 'ODISHA'})
print(df['State'].unique())

['ANDHRA PRADESH ' 'ODISHA' 'TAMIL NADU ' 'ANDHRA PRADESH']

In [16]:
#Fixing Type of Water Body string values
water_body_counts = df['Type of Water Body'].value_counts()
print("Count of each type of water body:")
print(water_body_counts)

Count of each type of water body:
Type of Water Body
MARINE     95
SEA        67
MARINE     31
BEACH      19
CREEK      12
CREEK       7
SEA         3
SEA         1
Name: count, dtype: int64

In [17]:
! git clone https://github.com/itskutush/Water-Quality-Analysis-using-GNN.git

Cloning into 'Water-Quality-Analysis-using-GNN'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (6/6), 595.33 KiB | 2.32 MiB/s, done.

In [22]:
! cd Water-Quality-Analysis-using-GNN

In [23]:
! git checkout -b feature/Data Analysis

fatal: not a git repository (or any of the parent directories): .git